// CLI-1: the options registry table (see src/opts.rs). One row per option; `env` = the environment
// variable it replaced (the startup guard rejects it by name). Keep rows sorted by env within the
// generated block; append new options at the end (no env).

pub const REG: &[Opt] = &[
    Opt { flag: "accept-debug", env: "GB10_ACCEPT_DEBUG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 MTP: print per-step acceptance / draft details" },
    Opt { flag: "attn-e-debug", env: "GB10_ATTN_E_DEBUG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 attention-E path debug prints" },
    Opt { flag: "attn-flash", env: "GB10_ATTN_FLASH", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 flash attention path (off = the pre-flash kernels)" },
    Opt { flag: "attn-p3", env: "GB10_ATTN_P3", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 P3 attention variant (opt-in)" },
    Opt { flag: "a-ctrl", env: "GB10_A_CTRL", ty: Ty::Choice(&["new", "fixed128", "old"]), def: "new", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP-A escape: lane control (fixed128 / old = the pre-WP03 control)" },
    Opt { flag: "a-off", env: "GB10_A_OFF", ty: Ty::Flag, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP-A escape: every WP-A lane fix off (the pre-WP03 behaviour)" },
    Opt { flag: "a-remclamp", env: "GB10_A_REMCLAMP", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP-A escape: remaining-budget clamp (off = unclamped)" },
    Opt { flag: "a-seam", env: "GB10_A_SEAM", ty: Ty::Choice(&["new", "headprime", "old"]), def: "new", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP-A escape: prime seam (headprime / old)" },
    Opt { flag: "a-taps", env: "GB10_A_TAPS", ty: Ty::Choice(&["lane", "shared"]), def: "lane", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP-A escape: shared = one tap buffer for every lane (the pre-WP03 clobber)" },
    Opt { flag: "a-xcheck", env: "GB10_A_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP03 cross-lane tap bit-compare every round (syncs)" },
    Opt { flag: "bench-logits-hash", env: "GB10_BENCH_LOGITS_HASH", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "bench: print a logits hash per step" },
    Opt { flag: "binv-section", env: "GB10_BINV_SECTION", ty: Ty::Choice(&["wp18", "moe_pf", "pf_hc", "gdn_tc"]), def: "all", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 --probe-binv: run only this section" },
    Opt { flag: "bisect-len", env: "GB10_BISECT_LEN", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSV4 TP bench: pad/truncate the prompt to exactly N tokens" },
    Opt { flag: "bmtp-diag", env: "GB10_BMTP_DIAG", ty: Ty::Choice(&["plain", "noprime"]), def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 bench-mtp diagnostic mode" },
    Opt { flag: "cap-debug", env: "GB10_CAP_DEBUG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "graph-capture debug prints" },
    Opt { flag: "dbg-mtp-only", env: "GB10_DBG_MTP_ONLY", ty: Ty::Text, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 MTP debug: restrict the debug dump to this sub-stage" },
    Opt { flag: "debug-hash", env: "GB10_DEBUG_HASH", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 per-step debug hashes" },
    Opt { flag: "device-loop", env: "GB10_DEVICE_LOOP", ty: Ty::Choice(&["on", "off", "1", "0", "true", "false"]), def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "device-resident token loop (NVFP4; under TP rides TpConfig)" },
    Opt { flag: "df2-capture", env: "GB10_DF2_CAPTURE", ty: Ty::Internal("--df2-capture on"), def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DFlash2 trunk tap capture (set by --df2-capture)" },
    Opt { flag: "df2-carry-len-only", env: "GB10_DF2_CARRY_LEN_ONLY", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DF2 carry diagnostic: carry the ring length only" },
    Opt { flag: "df2-det-dual", env: "GB10_DF2_DET_DUAL", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DF2 determinism probe: dual run" },
    Opt { flag: "df2-det-only", env: "GB10_DF2_DET_ONLY", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DF2 determinism probe: determinism check only" },
    Opt { flag: "df2-det-post", env: "GB10_DF2_DET_POST", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DF2 determinism probe: post-round check" },
    Opt { flag: "df2-gate-dump", env: "GB10_DF2_GATE_DUMP", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DF2 gate dump" },
    Opt { flag: "df2-mirror-threads", env: "GB10_DF2_MIRROR_THREADS", ty: Ty::Int, def: "auto", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DFlash2 mirror worker threads" },
    Opt { flag: "df2-qhead", env: "GB10_DF2_QHEAD", ty: Ty::Flag, def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DFlash2: plain-q head borrow (bf16 borrow only)" },
    Opt { flag: "df2-step-log", env: "GB10_DF2_STEP_LOG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DFlash2 per-step log" },
    Opt { flag: "df2-tp", env: "GB10_DF2_TP", ty: Ty::Internal("--spec-source dflash2*/dspark"), def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "keep the full lm_head for the DF2/DSpark round under TP (derived from --spec-source)" },
    Opt { flag: "dflash-attn-eager", env: "GB10_DFLASH_ATTN_EAGER", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DFlash v1: eager (untiled) drafter attention" },
    Opt { flag: "dflash-debug", env: "GB10_DFLASH_DEBUG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DFlash v1 debug prints" },
    Opt { flag: "dflash-step-log", env: "GB10_DFLASH_STEP_LOG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DFlash v1 per-step log" },
    Opt { flag: "dflash-tapdump", env: "GB10_DFLASH_TAPDUMP", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DFlash v1: dump the trunk taps to this path" },
    Opt { flag: "dheadp-cap", env: "GB10_DHEADP_CAP", ty: Ty::Int, def: "256", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DHEADP expansion cap (tunable dheadp.cap override)" },
    Opt { flag: "dheadp-off", env: "GB10_DHEADP_OFF", ty: Ty::Bool, def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DHEADP escape (tunable dheadp.off override)" },
    Opt { flag: "dhead-bits", env: "GB10_DHEAD_BITS", ty: Ty::Choice(&["1", "2", "4"]), def: "2", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DHEAD screen bits" },
    Opt { flag: "dhead-delta", env: "GB10_DHEAD_DELTA", ty: Ty::Float, def: "4.0", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DHEAD rescore margin" },
    Opt { flag: "dhead-off", env: "GB10_DHEAD_OFF", ty: Ty::Flag, def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DHEAD escape: the full draft head" },
    Opt { flag: "dhead-t", env: "GB10_DHEAD_T", ty: Ty::Int, def: "16", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DHEAD candidate count" },
    Opt { flag: "dhead-xcheck", env: "GB10_DHEAD_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DHEAD eager cross-check vs the full head" },
    Opt { flag: "dispatch-log", env: "GB10_DISPATCH_LOG", ty: Ty::Choice(&["1", "count", "assert"]), def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "dispatch assertion posture (count / assert)" },
    Opt { flag: "draft-dir", env: "GB10_DRAFT_DIR", ty: Ty::Internal("--draft-dir"), def: "unset", cat: Cat::Spec, scope: Scope::Spmd,
          help: "drafter artifact dir (set by --draft-dir)" },
    Opt { flag: "dspark-attn", env: "GB10_DSPARK_ATTN", ty: Ty::Text, def: "default", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSpark round attention selector (diagnostic)" },
    Opt { flag: "dspark-bisect", env: "GB10_DSPARK_BISECT", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark bisect mode" },
    Opt { flag: "dspark-block-pos", env: "GB10_DSPARK_BLOCK_POS", ty: Ty::Int, def: "0", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark block position override" },
    Opt { flag: "dspark-chain-a", env: "GB10_DSPARK_CHAIN_A", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSpark legacy chain A" },
    Opt { flag: "dspark-d0-plain", env: "GB10_DSPARK_D0_PLAIN", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSpark legacy plain d0" },
    Opt { flag: "dspark-debug", env: "GB10_DSPARK_DEBUG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark debug prints" },
    Opt { flag: "dspark-debug-ring", env: "GB10_DSPARK_DEBUG_RING", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark ring debug prints" },
    Opt { flag: "dspark-dump-step0", env: "GB10_DSPARK_DUMP_STEP0", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark: dump step 0 to this dir" },
    Opt { flag: "dspark-dump-steps", env: "GB10_DSPARK_DUMP_STEPS", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark: number of steps to dump" },
    Opt { flag: "dspark-fp8-logits", env: "GB10_DSPARK_FP8_LOGITS", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSpark fp8 draft LM head (also --dspark-fp8-head on the TP head)" },
    Opt { flag: "dspark-graph", env: "GB10_DSPARK_GRAPH", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSpark graphed round" },
    Opt { flag: "dspark-nomscale", env: "GB10_DSPARK_NOMSCALE", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSpark: no mscale (legacy)" },
    Opt { flag: "dspark-norm-g1", env: "GB10_DSPARK_NORM_G1", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSpark: legacy norm g1" },
    Opt { flag: "dspark-phase-ms", env: "GB10_DSPARK_PHASE_MS", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark per-phase ms timing (syncs)" },
    Opt { flag: "dspark-ring-blind", env: "GB10_DSPARK_RING_BLIND", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark ring-blind diagnostic" },
    Opt { flag: "dspark-rope-il", env: "GB10_DSPARK_ROPE_IL", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSpark interleaved rope (legacy)" },
    Opt { flag: "dspark-round-bisect", env: "GB10_DSPARK_ROUND_BISECT", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark round layer bisect" },
    Opt { flag: "dspark-round-trace", env: "GB10_DSPARK_ROUND_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark round trace" },
    Opt { flag: "dspark-step-log", env: "GB10_DSPARK_STEP_LOG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark per-step log" },
    Opt { flag: "dspark-tap-rev", env: "GB10_DSPARK_TAP_REV", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSpark reversed tap order" },
    Opt { flag: "dspark-tap-shift", env: "GB10_DSPARK_TAP_SHIFT", ty: Ty::Int, def: "0", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSpark tap shift" },
    Opt { flag: "dump-pfhash", env: "GB10_DUMP_PFHASH", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 prefill hash dumps" },
    Opt { flag: "e8-no-shard", env: "GB10_E8_NO_SHARD", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "E8 escape: keep the shared expert replicated under TP" },
    Opt { flag: "e9-no-fold", env: "GB10_E9_NO_FOLD", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "E9 escape: no programmatic dependent-launch overlap" },
    Opt { flag: "exact-gemm", env: "GB10_EXACT_GEMM", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "select the locked bit-exact GEMM kernels (tolerance-class fast paths are the default)" },
    Opt { flag: "exl3-a1b3", env: "GB10_EXL3_A1B3", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "A-once 3-bit expert entry (tunable moe.a1b3 override)" },
    Opt { flag: "exl3-chain-pair", env: "GB10_EXL3_CHAIN_PAIR", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "paired same-input chains (tunable override)" },
    Opt { flag: "exl3-chain-pair-check", env: "GB10_EXL3_CHAIN_PAIR_CHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 chain-pair eager cross-check (graphs off)" },
    Opt { flag: "exl3-conv-serial", env: "GB10_EXL3_CONV_SERIAL", ty: Ty::Flag, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "prefill conv serial (tunable pf.conv_par=0)" },
    Opt { flag: "exl3-dds-depth-bins", env: "GB10_EXL3_DDS_DEPTH_BINS", ty: Ty::Choice(&["on", "1", "off", "0"]), def: "auto", cat: Cat::Spec, scope: Scope::Spmd,
          help: "WP23 depth bins (default: on iff depth > the legacy max)" },
    Opt { flag: "exl3-dds-guard", env: "GB10_EXL3_DDS_GUARD", ty: Ty::Choice(&["on", "1", "off", "0"]), def: "auto", cat: Cat::Spec, scope: Scope::Spmd,
          help: "WP23 cost guard (default: on iff depth > the legacy max)" },
    Opt { flag: "exl3-dense-v3", env: "GB10_EXL3_DENSE_V3", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP13 dense attention v3 (tunable override)" },
    Opt { flag: "exl3-dense-xcheck", env: "GB10_EXL3_DENSE_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP13 dense attention eager cross-check" },
    Opt { flag: "exl3-draft-attn", env: "GB10_EXL3_DRAFT_ATTN", ty: Ty::Choice(&["legacy"]), def: "new", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "draft attention: legacy = the pre-WP path" },
    Opt { flag: "exl3-draft-graph", env: "GB10_EXL3_DRAFT_GRAPH", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 draft graphs (tunable override)" },
    Opt { flag: "exl3-dump8", env: "GB10_EXL3_DUMP8", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 8-bit trellis dump path at load" },
    Opt { flag: "exl3-esel-hist", env: "GB10_EXL3_ESEL_HIST", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 expert-selection histogram (printed cumulatively at every request finish and at exit)" },
    Opt { flag: "exl3-gather-xcheck", env: "GB10_EXL3_GATHER_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP14 QSA gather eager cross-check" },
    Opt { flag: "exl3-gdn-ring", env: "GB10_EXL3_GDN_RING", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "GDN state ring (off = the pre-ring path)" },
    Opt { flag: "exl3-gdn-ring-check", env: "GB10_EXL3_GDN_RING_CHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "GDN ring eager check" },
    Opt { flag: "exl3-gdn-tc-min", env: "GB10_EXL3_GDN_TC_MIN", ty: Ty::Int, def: "built-in", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "GDN tensor-core chunk min rows" },
    Opt { flag: "exl3-gdn-tc-prec", env: "GB10_EXL3_GDN_TC_PREC", ty: Ty::Text, def: "default", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "GDN tensor-core precision variant" },
    Opt { flag: "exl3-gdn-xcheck", env: "GB10_EXL3_GDN_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "GDN tensor-core eager cross-check" },
    Opt { flag: "exl3-head-fill", env: "GB10_EXL3_HEAD_FILL", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 head fill" },
    Opt { flag: "exl3-head-qsa", env: "GB10_EXL3_HEAD_QSA", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 QSA on the draft head (off = dense)" },
    Opt { flag: "exl3-moe-devroute", env: "GB10_EXL3_MOE_DEVROUTE", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 device-side MoE routing" },
    Opt { flag: "exl3-moe-epi-check", env: "GB10_EXL3_MOE_EPI_CHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 MoE epilogue check" },
    Opt { flag: "exl3-moe-grouped", env: "GB10_EXL3_MOE_GROUPED", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "prefill grouped expert launches (tunable override)" },
    Opt { flag: "exl3-moe-recon-min", env: "GB10_EXL3_MOE_RECON_MIN", ty: Ty::Int, def: "0", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "MoE reconstruct min rows" },
    Opt { flag: "exl3-mtp-head-n", env: "GB10_EXL3_MTP_HEAD_N", ty: Ty::Int, def: "auto", cat: Cat::Spec, scope: Scope::Spmd,
          help: "EXL3 MTP head count override" },
    Opt { flag: "exl3-mtp-k", env: "GB10_EXL3_MTP_K", ty: Ty::Int, def: "auto", cat: Cat::Spec, scope: Scope::Spmd,
          help: "EXL3 MTP depth k override" },
    Opt { flag: "exl3-no-graph", env: "GB10_EXL3_NO_GRAPH", ty: Ty::Flag, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3: no CUDA graphs (diagnostic escape)" },
    Opt { flag: "exl3-no-mtp", env: "GB10_EXL3_NO_MTP", ty: Ty::Flag, def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "EXL3: no MTP (diagnostics hatch ONLY, AGENTS 1b)" },
    Opt { flag: "exl3-no-ple", env: "GB10_EXL3_NO_PLE", ty: Ty::Flag, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3: no PLE (diagnostic)" },
    Opt { flag: "exl3-no-prefill-warmup", env: "GB10_EXL3_NO_PREFILL_WARMUP", ty: Ty::Flag, def: "off", cat: Cat::Serve, scope: Scope::Spmd,
          help: "skip the serve-boot prefill warmup" },
    Opt { flag: "exl3-pdl", env: "GB10_EXL3_PDL", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PDL per graph family (tunable override)" },
    Opt { flag: "exl3-pen-draft", env: "GB10_EXL3_PEN_DRAFT", ty: Ty::Bool, def: "on", cat: Cat::Spec, scope: Scope::Spmd,
          help: "penalties applied to drafts" },
    Opt { flag: "exl3-poison", env: "GB10_EXL3_POISON", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 scratch poisoning" },
    Opt { flag: "exl3-prefix", env: "GB10_EXL3_PREFIX", ty: Ty::Internal("--prefix-cache on"), def: "off", cat: Cat::Kv, scope: Scope::Spmd,
          help: "EXL3 prefix-cache snapshots (set by --prefix-cache)" },
    Opt { flag: "exl3-qsa-splits-dec", env: "GB10_EXL3_QSA_SPLITS_DEC", ty: Ty::Int, def: "32", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "QSA decode splits (N-class tunable override)" },
    Opt { flag: "exl3-recon-min", env: "GB10_EXL3_RECON_MIN", ty: Ty::Int, def: "built-in", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "dense reconstruct min rows" },
    Opt { flag: "exl3-reprime", env: "GB10_EXL3_REPRIME", ty: Ty::Choice(&["0", "full", "on"]), def: "on", cat: Cat::Spec, scope: Scope::Spmd,
          help: "device re-prime mode (0 = off, full)" },
    Opt { flag: "exl3-reprime-eager", env: "GB10_EXL3_REPRIME_EAGER", ty: Ty::Flag, def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "eager device re-prime" },
    Opt { flag: "exl3-reprime-graph", env: "GB10_EXL3_REPRIME_GRAPH", ty: Ty::Bool, def: "on", cat: Cat::Spec, scope: Scope::Spmd,
          help: "graphed device re-prime (tunable override)" },
    Opt { flag: "exl3-round-prof", env: "GB10_EXL3_ROUND_PROF", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "per-round phase profiler" },
    Opt { flag: "exl3-router-fused", env: "GB10_EXL3_ROUTER_FUSED", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "fused router (tunable override)" },
    Opt { flag: "exl3-router-ks", env: "GB10_EXL3_ROUTER_KS", ty: Ty::Text, def: "built-in", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "router split-K list" },
    Opt { flag: "exl3-router-rows", env: "GB10_EXL3_ROUTER_ROWS", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "prefill router rows32 twin (tunable override)" },
    Opt { flag: "exl3-router-xcheck", env: "GB10_EXL3_ROUTER_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "fused router eager cross-check" },
    Opt { flag: "exl3-route-check", env: "GB10_EXL3_ROUTE_CHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 routing check (graphs off)" },
    Opt { flag: "exl3-score-mr", env: "GB10_EXL3_SCORE_MR", ty: Ty::Choice(&["0", "off", "1", "on", "generic"]), def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP04 bucket-free scorer (0 = bucketed; generic body)" },
    Opt { flag: "exl3-score-mr-ctas", env: "GB10_EXL3_SCORE_MR_CTAS", ty: Ty::Int, def: "4", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP04 scorer CTAs/SM (tunable override)" },
    Opt { flag: "exl3-score-xcheck", env: "GB10_EXL3_SCORE_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP04 scorer eager cross-check" },
    Opt { flag: "exl3-sel-gather", env: "GB10_EXL3_SEL_GATHER", ty: Ty::Text, def: "-1 (auto)", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP04 gather variant pin (tunable override)" },
    Opt { flag: "exl3-sel-vec", env: "GB10_EXL3_SEL_VEC", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "legacy gather float4 twin (tunable override)" },
    Opt { flag: "exl3-sel-xcheck", env: "GB10_EXL3_SEL_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP04 gather eager cross-check" },
    Opt { flag: "exl3-topk-v2", env: "GB10_EXL3_TOPK_V2", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP04 top-k asc2 (tunable override)" },
    Opt { flag: "exl3-topk-xcheck", env: "GB10_EXL3_TOPK_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP04 top-k eager cross-check" },
    Opt { flag: "exl3-tp-fastctl", env: "GB10_EXL3_TP_FASTCTL", ty: Ty::Bool, def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP fast control plane" },
    Opt { flag: "exl3-tp-ident", env: "GB10_EXL3_TP_IDENT", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 TP served ident digests across ranks every lockstep point" },
    Opt { flag: "exl3-tp-preverify", env: "GB10_EXL3_TP_PREVERIFY", ty: Ty::Bool, def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP pre-verify agree" },
    Opt { flag: "exl3-wide-mt", env: "GB10_EXL3_WIDE_MT", ty: Ty::Choice(&["1", "2", "4", "8"]), def: "0 (the MT rule; 4 for dense)", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "wide-M trellis GEMM m-tiles per CTA (engine override; also the --bench-exl3-wide MT)" },
    Opt { flag: "f9-xhash", env: "GB10_F9_XHASH", ty: Ty::IntFlag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 F9 cross-hash dumps (1|2|3)" },
    Opt { flag: "fa-prefill", env: "GB10_FA_PREFILL", ty: Ty::Bool, def: "on", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 tensor-core flash-attention prefill" },
    Opt { flag: "fold-xchain-dump", env: "GB10_FOLD_XCHAIN_DUMP", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 fold cross-chain dump path" },
    Opt { flag: "fp8-prefill", env: "GB10_FP8_PREFILL", ty: Ty::Bool, def: "on", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "native e4m3 W8A8 prefill lane" },
    Opt { flag: "fuse-residual", env: "GB10_FUSE_RESIDUAL", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "FFN-epilogue residual fusion (E14)" },
    Opt { flag: "gdn-chunk", env: "GB10_GDN_CHUNK", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 chunkwise GDN prefill (v1)" },
    Opt { flag: "gdn-chunk2", env: "GB10_GDN_CHUNK2", ty: Ty::Bool, def: "on", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 chunkwise GDN prefill v2" },
    Opt { flag: "gdn-oldstage", env: "GB10_GDN_OLDSTAGE", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 GDN old staging kernel" },
    Opt { flag: "gdn-rollback-d2d", env: "GB10_GDN_ROLLBACK_D2D", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 GDN rollback via D2D copies (escape)" },
    Opt { flag: "gdn-split", env: "GB10_GDN_SPLIT", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 split chunked GDN prefill (diagnostic variant)" },
    Opt { flag: "gdn-time", env: "GB10_GDN_TIME", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 GDN per-layer timing (syncs)" },
    Opt { flag: "gdn-xcheck", env: "GB10_GDN_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 GDN eager cross-check" },
    Opt { flag: "splitk-gemm", env: "GB10_GEMM_SPLITK", ty: Ty::IntFlag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 serving-GEMM split-K (bare = per-shape auto; 0 = off; N>=2 forces N, single-node only)" },
    Opt { flag: "graph", env: "GB10_GRAPH", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSV4 decode graphs" },
    Opt { flag: "graph-debug", env: "GB10_GRAPH_DEBUG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSV4 graph debug prints" },
    Opt { flag: "graph-noupdates", env: "GB10_GRAPH_NOUPDATES", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSV4 graph: skip node updates" },
    Opt { flag: "graph-upload", env: "GB10_GRAPH_UPLOAD", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSV4 graph upload" },
    Opt { flag: "hc-fp16", env: "GB10_HC_FP16", ty: Ty::Flag, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 hyper-connection mixers in bit-exact fp16 (int8 is the default)" },
    Opt { flag: "hc-fuse", env: "GB10_HC_FUSE", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 hc fuse" },
    Opt { flag: "hc-int8", env: "GB10_HC_INT8", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 int8 hc mixers (off = fp16; prefer --hc-fp16)" },
    Opt { flag: "hc-int8-check", env: "GB10_HC_INT8_CHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 hc int8 check (graphs off)" },
    Opt { flag: "hc-mix4", env: "GB10_HC_MIX4", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "shared inject reduction tree (tunable override)" },
    Opt { flag: "hc-rb", env: "GB10_HC_RB", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "row-batched int8 hc mixer (tunable override)" },
    Opt { flag: "hc-step-check", env: "GB10_HC_STEP_CHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 hc step eager check" },
    Opt { flag: "inject-panic-steps", env: "GB10_INJECT_PANIC_STEPS", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "test drill: inject a scheduler panic at decode step N" },
    Opt { flag: "kv-cache", env: "GB10_KV_CACHE", ty: Ty::Internal("--kv-cache f32/f16/fp8/q8"), def: "default", cat: Cat::Kv, scope: Scope::Spmd,
          help: "EXL3 KV cache format (set by --kv-cache)" },
    Opt { flag: "kv-k8v4", env: "GB10_KV_K8V4", ty: Ty::Internal("--kv-cache k8v4"), def: "off", cat: Cat::Kv, scope: Scope::Spmd,
          help: "NVFP4 int8-K + q4-V KV cache (set by --kv-cache k8v4)" },
    Opt { flag: "kv-k8v8", env: "GB10_KV_K8V8", ty: Ty::Internal("--kv-cache k8v8"), def: "off", cat: Cat::Kv, scope: Scope::Spmd,
          help: "NVFP4 int8 K+V KV cache (set by --kv-cache k8v8)" },
    Opt { flag: "kv-mirror-budget", env: "GB10_KV_MIRROR_BUDGET", ty: Ty::Int, def: "32768", cat: Cat::Kv, scope: Scope::Spmd,
          help: "packed-KV mirror budget (positions)" },
    Opt { flag: "kv-quant", env: "GB10_KV_QUANT", ty: Ty::Internal("--kv-cache q4"), def: "off", cat: Cat::Kv, scope: Scope::Spmd,
          help: "NVFP4 4-bit KV cache (set by --kv-cache q4)" },
    Opt { flag: "kv-tq", env: "GB10_KV_TQ", ty: Ty::Internal("--kv-cache tq/tq3"), def: "off", cat: Cat::Kv, scope: Scope::Spmd,
          help: "NVFP4 TurboQuant KV (1 = b2 K, 3 = b3 K; set by --kv-cache tq/tq3)" },
    Opt { flag: "layer-csum", env: "GB10_LAYER_CSUM", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 per-layer checksums" },
    Opt { flag: "layer-fullhash", env: "GB10_LAYER_FULLHASH", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 per-layer full hashes" },
    Opt { flag: "lmh-had", env: "GB10_LMH_HAD", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W3/LMH fused output Hadamard (tunable override)" },
    Opt { flag: "lmh-nst", env: "GB10_LMH_NST", ty: Ty::Choice(&["4", "6", "8"]), def: "6", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W3/LMH cp.async ring depth (tunable override)" },
    Opt { flag: "lmh-off", env: "GB10_LMH_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W3/LMH escape (tunable override)" },
    Opt { flag: "lmh-xcheck", env: "GB10_LMH_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "W3/LMH eager cross-check" },
    Opt { flag: "load-force", env: "GB10_LOAD_FORCE", ty: Ty::Choice(&["1", "unsafe"]), def: "off", cat: Cat::Load, scope: Scope::Spmd,
          help: "bypass the load memory guard (unsafe = also on qwen4_exp)" },
    Opt { flag: "load-pipe-cap-gb", env: "GB10_LOAD_PIPE_CAP_GB", ty: Ty::Int, def: "built-in", cat: Cat::Load, scope: Scope::Spmd,
          help: "load pipeline cap (GB)" },
    Opt { flag: "load-shard-trace", env: "GB10_LOAD_SHARD_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "load: shard trace" },
    Opt { flag: "load-sync-upload", env: "GB10_LOAD_SYNC_UPLOAD", ty: Ty::Flag, def: "off", cat: Cat::Load, scope: Scope::Spmd,
          help: "load: synchronous uploads" },
    Opt { flag: "load-workers", env: "GB10_LOAD_WORKERS", ty: Ty::Int, def: "8", cat: Cat::Load, scope: Scope::Spmd,
          help: "load worker threads" },
    Opt { flag: "loop-trace", env: "GB10_LOOP_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "scheduler loop trace" },
    Opt { flag: "max-seq-len", env: "GB10_MAX_SEQ_LEN", ty: Ty::Int, def: "per mode", cat: Cat::Serve, scope: Scope::Spmd,
          help: "max context / KV depth (the DSV4 TP paths honour it as the override)" },
    Opt { flag: "mem-trace", env: "GB10_MEM_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Local,
          help: "1 Hz unified-memory timeline" },
    Opt { flag: "mem-watchdog-gb", env: "GB10_MEM_WATCHDOG_GB", ty: Ty::Float, def: "5", cat: Cat::Load, scope: Scope::Local,
          help: "host-memory watchdog floor in GB (0 = off)" },
    Opt { flag: "moe-coop", env: "GB10_MOE_COOP", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "cooperative expert stream (tunable override)" },
    Opt { flag: "moe-fh", env: "GB10_MOE_FH", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "fused per-expert Hadamards (tunable override)" },
    Opt { flag: "moe-fold", env: "GB10_MOE_FOLD", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "E12 fold the shared expert into the grouped MoE launches (opt-in)" },
    Opt { flag: "moe-fold-debug", env: "GB10_MOE_FOLD_DEBUG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "E12 fold debug prints" },
    Opt { flag: "moe-grouped-min", env: "GB10_MOE_GROUPED_MIN", ty: Ty::Int, def: "built-in", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 grouped MoE min rows" },
    Opt { flag: "moe-grouped-wide", env: "GB10_MOE_GROUPED_WIDE", ty: Ty::Bool, def: "on", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 wide grouped MoE" },
    Opt { flag: "moe-gu-fold", env: "GB10_MOE_GU_FOLD", ty: Ty::Int, def: "6 (tuned)", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "fold xq_had_suh_multi into the WP20 gate/up prologue up to width N, 0..16 (tunable moe.gu_fold override)" },
    Opt { flag: "moe-native-pf", env: "GB10_MOE_NATIVE_PF", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 native MoE prefill" },
    Opt { flag: "moe-no-fold", env: "GB10_MOE_NO_FOLD", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "E12 fold escape (the separate-launch shared MLP)" },
    Opt { flag: "moe-shovl", env: "GB10_MOE_SHOVL", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "shared-expert overlap on the WP20 path (tunable override)" },
    Opt { flag: "moe-variant", env: "GB10_MOE_VARIANT", ty: Ty::Choice(&["plain", "u4", "x2", "rast", "lb5", "lb4", "pdl"]), def: "plain", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 MoE kernel variant" },
    Opt { flag: "mtp-cover", env: "GB10_MTP_COVER", ty: Ty::Int, def: "0", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 MTP coverage probe layer count" },
    Opt { flag: "mtp-cover-out", env: "GB10_MTP_COVER_OUT", ty: Ty::Path, def: "/tmp/mtp_cover.csv", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 MTP coverage probe CSV path" },
    Opt { flag: "mtp-dispatch-trace", env: "GB10_MTP_DISPATCH_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "MTP dispatch trace" },
    Opt { flag: "mtp-dump", env: "GB10_MTP_DUMP", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 MTP dump dir (graphs off)" },
    Opt { flag: "mtp-garbage-draft", env: "GB10_MTP_GARBAGE_DRAFT", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "test drill: garbage drafts (losslessness negative control)" },
    Opt { flag: "mtp-lossless-audit", env: "GB10_MTP_LOSSLESS_AUDIT", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "MTP losslessness audit" },
    Opt { flag: "mxfp4", env: "GB10_MXFP4", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "MXFP4-native serving mode (fp4 decode/verify GEMMs on the OMMA path)" },
    Opt { flag: "mxfp4-allow-experts", env: "GB10_MXFP4_ALLOW_EXPERTS", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "MXFP4: allow expert tensors" },
    Opt { flag: "mxfp4-economy", env: "GB10_MXFP4_ECONOMY", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "MXFP4 economy (drop the bf16 copies)" },
    Opt { flag: "mxfp4-fused", env: "GB10_MXFP4_FUSED", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "MXFP4 fused kernels" },
    Opt { flag: "mxfp4-fused-prefill", env: "GB10_MXFP4_FUSED_PREFILL", ty: Ty::Bool, def: "on", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "MXFP4 fused prefill" },
    Opt { flag: "mxfp4-mtp-native", env: "GB10_MXFP4_MTP_NATIVE", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "MXFP4: native MTP head (allowlist escape)" },
    Opt { flag: "mxfp4-prefill", env: "GB10_MXFP4_PREFILL", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "MXFP4 native prefill" },
    Opt { flag: "mxfp4-prefill-check", env: "GB10_MXFP4_PREFILL_CHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "MXFP4 prefill A/B check" },
    Opt { flag: "mxfp4-xchain-capture", env: "GB10_MXFP4_XCHAIN_CAPTURE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "MXFP4 cross-chain capture hooks (the probes arm it)" },
    Opt { flag: "no-attn-e", env: "GB10_NO_ATTN_E", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4: no attention-E path" },
    Opt { flag: "no-decode-graphs", env: "GB10_NO_DECODE_GRAPHS", ty: Ty::Flag, def: "off", cat: Cat::Serve, scope: Scope::Spmd,
          help: "disable decode CUDA graphs (diagnostic)" },
    Opt { flag: "no-df2-graph", env: "GB10_NO_DF2_GRAPH", ty: Ty::Flag, def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DFlash2: no round graph (escape)" },
    Opt { flag: "no-df2-inject-graph", env: "GB10_NO_DF2_INJECT_GRAPH", ty: Ty::Flag, def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DFlash2: no inject graph (escape)" },
    Opt { flag: "no-df2-q2stage", env: "GB10_NO_DF2_Q2STAGE", ty: Ty::Flag, def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "DFlash2: no q2 staging (escape)" },
    Opt { flag: "no-fused-perhead-rope", env: "GB10_NO_FUSED_PERHEAD_ROPE", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4: unfused per-head rope (escape)" },
    Opt { flag: "no-gqpack", env: "GB10_NO_GQPACK", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4: no GQA packing (escape)" },
    Opt { flag: "no-qkv-view", env: "GB10_NO_QKV_VIEW", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4: old qkv pipeline (escape)" },
    Opt { flag: "no-verify-graph", env: "GB10_NO_VERIFY_GRAPH", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4: no verify graph (escape; some probes set it)" },
    Opt { flag: "p1-time-all", env: "GB10_P1_TIME_ALL", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 bench: time every chunk size" },
    Opt { flag: "packed-cache", env: "GB10_PACKED_CACHE", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSV4 packed fp4 cache" },
    Opt { flag: "pair-seq", env: "GB10_PAIR_SEQ", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSV4 sequential pair attention" },
    Opt { flag: "pf4-trace", env: "GB10_PF4_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "MXFP4 prefill trace" },
    Opt { flag: "pf8-check", env: "GB10_PF8_CHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "fp8 prefill check" },
    Opt { flag: "pf8-dump", env: "GB10_PF8_DUMP", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "fp8 prefill dump" },
    Opt { flag: "pf8-trace", env: "GB10_PF8_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "fp8 prefill trace" },
    Opt { flag: "pfx1-headkv-poison", env: "GB10_PFX1_HEADKV_POISON", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "PFX1 head-KV poison drill" },
    Opt { flag: "pfx1-off", env: "GB10_PFX1_OFF", ty: Ty::Text, def: "unset", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PFX1 escape (1|all|<parts>)" },
    Opt { flag: "pfx1-rows8-max", env: "GB10_PFX1_ROWS8_MAX", ty: Ty::Int, def: "built-in", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PFX1 rows8 max rows" },
    Opt { flag: "pf-dump", env: "GB10_PF_DUMP", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 prefill dump" },
    Opt { flag: "pf-gdn-scan", env: "GB10_PF_GDN_SCAN", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "chunkwise GDN prefill scan re-scheduled tc2 (tunable override)" },
    Opt { flag: "pf-hc-fuse", env: "GB10_PF_HC_FUSE", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "prefill hc inject+norm / mix fused (tunable override)" },
    Opt { flag: "pf-mixer4", env: "GB10_PF_MIXER4", ty: Ty::Text, def: "unset", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 prefill 4-bit mixer set (safe | all)" },
    Opt { flag: "pf-moe-fold", env: "GB10_PF_MOE_FOLD", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "prefill MoE glue folded into the expert epilogues (tunable override)" },
    Opt { flag: "pf-moe-kernel", env: "GB10_PF_MOE_KERNEL", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "pipelined prefill MoE expert kernel (tunable override)" },
    Opt { flag: "pf-moe-mt-pe", env: "GB10_PF_MOE_MT_PE", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP19 per-expert MT (tunable override)" },
    Opt { flag: "pf-moe-pf2", env: "GB10_PF_MOE_PF2", ty: Ty::Int, def: "3", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "prefill MoE smem trellis ring mask 0..15 (tunable override)" },
    Opt { flag: "no-pf-qkv-fast", env: "GB10_PF_QKV_FAST", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4: disable the fast prefill qkv path" },
    Opt { flag: "pf-rm-nocache", env: "GB10_PF_RM_NOCACHE", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 prefill: no row-major cache" },
    Opt { flag: "ple-offload", env: "GB10_PLE_OFFLOAD", ty: Ty::Choice(&["ssd", "none", "off", "gpu"]), def: "none", cat: Cat::Load, scope: Scope::Spmd,
          help: "qwen4_exp: keep the ~31 GB PLE n-gram table on SSD (ssd) or device-resident (none)" },
    Opt { flag: "ple-ram", env: "GB10_PLE_RAM", ty: Ty::Choice(&["auto", "ram", "ssd", "on", "off"]), def: "auto", cat: Cat::Load, scope: Scope::Spmd,
          help: "EXL3 n-gram (PLE) table location: ram = load it into memory (~31 GB on Qwen3.8-Flash-Next 3.05); ssd = read rows from disk through the page cache (frees that memory for lanes / context; identical output, ~1-2% slower decode); auto = decide after the boot has allocated everything else: RAM iff the table + 16 GiB stay free. on/off = old spellings of ram/ssd" },
    Opt { flag: "ple-ssd-cache-rows", env: "GB10_PLE_SSD_CACHE_ROWS", ty: Ty::Int, def: "262144", cat: Cat::Load, scope: Scope::Spmd,
          help: "PLE SSD row cache capacity" },
    Opt { flag: "ple-ssd-threads", env: "GB10_PLE_SSD_THREADS", ty: Ty::Int, def: "32", cat: Cat::Load, scope: Scope::Spmd,
          help: "PLE SSD reader threads" },
    Opt { flag: "ple-trace", env: "GB10_PLE_TRACE", ty: Ty::Text, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "PLE trace" },
    Opt { flag: "ple-xcheck", env: "GB10_PLE_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "PLE eager cross-check" },
    Opt { flag: "pq8-flash", env: "GB10_PQ8_FLASH", ty: Ty::Choice(&["0", "off", "1", "on", "causal"]), def: "causal", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PQ8 prefill flash kernel (0 = flash256, 1 = bitwise twin, causal = default)" },
    Opt { flag: "pq8-gather", env: "GB10_PQ8_GATHER", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PQ8 q8 prefill gather (tunable override)" },
    Opt { flag: "pq8-kvw", env: "GB10_PQ8_KVW", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PQ8 row-parallel KV writer (tunable override)" },
    Opt { flag: "pq8-off", env: "GB10_PQ8_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PQ8 escape (every PQ8 item off)" },
    Opt { flag: "pq8-xcheck", env: "GB10_PQ8_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "PQ8 eager cross-check" },
    Opt { flag: "prefillx-expect-sig", env: "GB10_PREFILLX_EXPECT_SIG", ty: Ty::Text, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "prefillx probe: expected signature" },
    Opt { flag: "prefillx-qsa-keys", env: "GB10_PREFILLX_QSA_KEYS", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "prefillx probe: dump QSA keys" },
    Opt { flag: "prefillx-rel", env: "GB10_PREFILLX_REL", ty: Ty::IntFlag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "prefillx probe: rel-L2 report (2 = verbose)" },
    Opt { flag: "prefillx-tier", env: "GB10_PREFILLX_TIER", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "prefillx probe: tier report" },
    Opt { flag: "prefillx-ulp", env: "GB10_PREFILLX_ULP", ty: Ty::Text, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "prefillx probe: ULP list" },
    Opt { flag: "prefillx-widths", env: "GB10_PREFILLX_WIDTHS", ty: Ty::Text, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "prefillx probe: widths list" },
    Opt { flag: "prefill-bf16-binv", env: "GB10_PREFILL_BF16_BINV", ty: Ty::Bool, def: "on", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 bf16 prefill batch-invariance path" },
    Opt { flag: "prefill-reps", env: "GB10_PREFILL_REPS", ty: Ty::Int, def: "1", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 prefill bench reps" },
    Opt { flag: "prefill-trace", env: "GB10_PREFILL_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "prefill trace (every family)" },
    Opt { flag: "prefill-warmup", env: "GB10_PREFILL_WARMUP", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 prefill bench warmup" },
    Opt { flag: "prefix-grid-reuse", env: "GB10_PREFIX_GRID_REUSE", ty: Ty::Bool, def: "on", cat: Cat::Kv, scope: Scope::Spmd,
          help: "prefix-cache grid reuse" },
    Opt { flag: "prefix-tail-ckpt", env: "GB10_PREFIX_TAIL_CKPT", ty: Ty::Choice(&["0", "1", "2"]), def: "1", cat: Cat::Kv, scope: Scope::Spmd,
          help: "tail (message-boundary) prefix checkpoints (tunable prefix.tail_ckpt override; owner default 1)" },
    Opt { flag: "psk", env: "GB10_PSK", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PSK opt-in (tunable override)" },
    Opt { flag: "psk-g", env: "GB10_PSK_G", ty: Ty::Text, def: "0 (auto)", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PSK persistent split-K grid per shape" },
    Opt { flag: "psk-off", env: "GB10_PSK_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PSK escape" },
    Opt { flag: "psk-pf", env: "GB10_PSK_PF", ty: Ty::Int, def: "1", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "PSK trellis L2 prefetch distance 0..127" },
    Opt { flag: "psk-xcheck", env: "GB10_PSK_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "PSK eager cross-check" },
    Opt { flag: "q4-dense-attn", env: "GB10_Q4_DENSE_ATTN", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 q4 dense attention" },
    Opt { flag: "qsa-dump", env: "GB10_QSA_DUMP", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 QSA dumps" },
    Opt { flag: "qsa-dump-layer", env: "GB10_QSA_DUMP_LAYER", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 QSA dump layer" },
    Opt { flag: "qsa-exl3", env: "GB10_QSA_EXL3", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 QSA (off = dense attention)" },
    Opt { flag: "qsa-pool", env: "GB10_QSA_POOL", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 QSA pooling" },
    Opt { flag: "qsa-rowdump-layer", env: "GB10_QSA_ROWDUMP_LAYER", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 QSA row dump layer" },
    Opt { flag: "qsa-scalar", env: "GB10_QSA_SCALAR", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 scalar QSA" },
    Opt { flag: "qsa-select", env: "GB10_QSA_SELECT", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "latency-lean QSA top-k select asc3 (tunable override)" },
    Opt { flag: "qsa-sel-v1", env: "GB10_QSA_SEL_V1", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 QSA select v1" },
    Opt { flag: "qsa-time", env: "GB10_QSA_TIME", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "QSA timing (syncs)" },
    Opt { flag: "rdma-dev", env: "GB10_RDMA_DEV", ty: Ty::Text, def: "rocep1s0f1", cat: Cat::Tp, scope: Scope::Local,
          help: "RDMA device(s): <rail1>[,<rail2>]" },
    Opt { flag: "reprime-xcheck", env: "GB10_REPRIME_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "re-prime eager cross-check" },
    Opt { flag: "rope-yarn-factor", env: "GB10_ROPE_YARN_FACTOR", ty: Ty::Internal("--rope-yarn-factor"), def: "1.0", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "trunk YaRN rope factor (set by --rope-yarn-factor)" },
    Opt { flag: "round-trace", env: "GB10_ROUND_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DFlash2 round trace" },
    Opt { flag: "router-coal", env: "GB10_ROUTER_COAL", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "router fold with coalesced weight staging (tunable override)" },
    Opt { flag: "spec-pass", env: "GB10_SPEC_PASS", ty: Ty::Text, def: "default", cat: Cat::Spec, scope: Scope::Spmd,
          help: "spec-pass mode (diagnostic)" },
    Opt { flag: "spec-pass-q", env: "GB10_SPEC_PASS_Q", ty: Ty::Float, def: "built-in", cat: Cat::Spec, scope: Scope::Spmd,
          help: "spec-pass q" },
    Opt { flag: "spec-pass-skew", env: "GB10_SPEC_PASS_SKEW", ty: Ty::Int, def: "unset", cat: Cat::Spec, scope: Scope::Spmd,
          help: "spec-pass skew" },
    Opt { flag: "spec-pass-xcheck", env: "GB10_SPEC_PASS_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "spec-pass eager cross-check" },
    Opt { flag: "spec-ratio-dhead", env: "GB10_SPEC_RATIO_DHEAD", ty: Ty::Bool, def: "on", cat: Cat::Spec, scope: Scope::Spmd,
          help: "real-q (ratio) draft passes on DHEAD (tunable spec.ratio_dhead override; owner default on)" },
    Opt { flag: "state-tap", env: "GB10_STATE_TAP", ty: Ty::Bool, def: "on", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 state tap" },
    Opt { flag: "step-topk-dir", env: "GB10_STEP_TOPK_DIR", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 step top-k dump dir" },
    Opt { flag: "tail-fixed", env: "GB10_TAIL_FIXED", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "NVFP4 fixed tail" },
    Opt { flag: "tpc-debug", env: "GB10_TPC_DEBUG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "TP config debug print" },
    Opt { flag: "tp-accept", env: "GB10_TP_ACCEPT", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "TP bench_accept depth (set = run the accept branch)" },
    Opt { flag: "tp-agree-drill", env: "GB10_TP_AGREE_DRILL", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Local,
          help: "test drill: corrupt THIS rank's agree hash at step N (per box: set it on the node's own command line for a one-sided fault)" },
    Opt { flag: "tp-batch-probe", env: "GB10_TP_BATCH_PROBE", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "TP batch probe width" },
    Opt { flag: "tp-binv-tp", env: "GB10_TP_BINV_TP", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "TP batch-invariance probe (also --probe-binv-tp)" },
    Opt { flag: "tp-boot-delay", env: "GB10_TP_BOOT_DELAY", ty: Ty::Text, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "test drill: <rank>:<seconds> sleep before the boot rendezvous" },
    Opt { flag: "tp-cache", env: "GB10_TP_CACHE", ty: Ty::Path, def: "~/.cache", cat: Cat::Tp, scope: Scope::Local,
          help: "node blob cache dir" },
    Opt { flag: "tp-capture", env: "GB10_TP_CAPTURE", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "TP debug capture path" },
    Opt { flag: "tp-dds-prior", env: "GB10_TP_DDS_PRIOR", ty: Ty::Text, def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "WP23 cost-guard prior on TP lanes: on = 2.7 ms/draft at TP=2, 2.1 at TP=4 (estimate), off = 6.0, or <ms>" },
    Opt { flag: "tp-decode-ctx", env: "GB10_TP_DECODE_CTX", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "TP DecodeCtx probe context" },
    Opt { flag: "tp-dec-blocks", env: "GB10_TP_DEC_BLOCKS", ty: Ty::Int, def: "8", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP decode K2 grid blocks" },
    Opt { flag: "tp-dec-grecv", env: "GB10_TP_DEC_GRECV", ty: Ty::Bool, def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP decode GPU receive (off = cpu_done only)" },
    Opt { flag: "tp-dec-xport", env: "GB10_TP_DEC_XPORT", ty: Ty::Bool, def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP decode transport (off = the serial pair)" },
    Opt { flag: "tp-dflash", env: "GB10_TP_DFLASH", ty: Ty::Flag, def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "NVFP4 TP DFlash drafter one-shot generate" },
    Opt { flag: "tp-dh-shard", env: "GB10_TP_DH_SHARD", ty: Ty::Bool, def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP sharded MTP-head screen" },
    Opt { flag: "tp-diag", env: "GB10_TP_DIAG", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "TP transport diagnostics" },
    Opt { flag: "ep-deal", env: "GB10_TP_EP_DEAL", ty: Ty::Choice(&["interleave", "contig", "freq"]), def: "interleave", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP static expert deal; freq = committed per-layer frequency-balanced table (world 2 and world 4; opt-in, output-changing)" },
    Opt { flag: "tp-ep-deal-file", env: "GB10_TP_EP_DEAL_FILE", ty: Ty::Path, def: "committed table", cat: Cat::Diag, scope: Scope::Spmd,
          help: "--ep-deal freq: an alternative deal table" },
    Opt { flag: "spec-lanes-max", env: "", ty: Ty::Text, def: "auto", cat: Cat::Spec, scope: Scope::Spmd,
          help: "EXL3 load-adaptive batching (CF-P1e): speculative (MTP) rounds run one lane at a time, so aggregate speed stops scaling past one lane, while ONE plain batched step serves every busy lane. auto (default) = each round picks the arm with the higher estimated aggregate tokens/s (measured per-lane speculative speed vs the measured shared-step time; speculation pays more on high-acceptance content, batching wins as lanes grow); N = share one plain step only with MORE than N busy lanes; 0 = never (always serial speculation). The lanes' MTP heads stay in sync across shared steps, so speculation resumes as load drops; a single busy lane always speculates (single-stream path unchanged). Greedy output is identical in every mode" },
    Opt { flag: "exl3-gu-kch", env: "", ty: Ty::Int, def: "2", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 MoE 10..16-row calls (packed verify / >8 lanes): K-chunks the gate/up A-once staging (CF-P1e 16-row class; bit-identical, keeps 2-3 CTAs per SM): 2 (default) | 4 | 0 = off (the legacy barrier body at those widths). Rows <= 9 are unaffected" },
    Opt { flag: "exl3-route-log", env: "", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 diagnostic: write every decode/verify MoE call's expert ids (layer, rows, ids) to DIR/route_NNNN.bin at each request finish (cross-lane expert-overlap study)" },
    Opt { flag: "exl3-ple-dump", env: "", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 diagnostic (CF-P1g oracle): after the n-gram table is built, write the production-path embeddings of 1,536 deterministic token positions (tokens, row ids, 2,560 fp16 values each) to FILE and exit; scripts/ple_oracle.py compares them with exllamav3's own hashing + codec" },
    Opt { flag: "tp-ep-hist", env: "GB10_TP_EP_HIST", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "EXL3 TP expert histogram dump" },
    Opt { flag: "tp-fp32-partials", env: "GB10_TP_FP32_PARTIALS", ty: Ty::Flag, def: "off", cat: Cat::Tp, scope: Scope::Spmd,
          help: "NVFP4 TP fp32 partials" },
    Opt { flag: "tp-gpu-recv", env: "GB10_TP_GPU_RECV", ty: Ty::Bool, def: "auto (TpConfig)", cat: Cat::Tp, scope: Scope::Spmd,
          help: "NVFP4 TP GPU-direct all-reduce receive (on / off; unset = the shipped config)" },
    Opt { flag: "tp-graph", env: "GB10_TP_GRAPH", ty: Ty::Flag, def: "off", cat: Cat::Tp, scope: Scope::Spmd,
          help: "NVFP4 TP decode graphs" },
    Opt { flag: "tp-head-proof", env: "GB10_TP_HEAD_PROOF", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 TP head proof" },
    Opt { flag: "tp-head-proof-fault", env: "GB10_TP_HEAD_PROOF_FAULT", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Local,
          help: "test drill: NVFP4 TP head-proof fault on THIS rank (per box)" },
    Opt { flag: "tp-ks-target", env: "GB10_TP_KS_TARGET", ty: Ty::Int, def: "auto", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP split-K target" },
    Opt { flag: "tp-mtp", env: "GB10_TP_MTP", ty: Ty::Internal("--mtp on"), def: "off", cat: Cat::Spec, scope: Scope::Spmd,
          help: "NVFP4 TP bench MTP (set by --mtp on)" },
    Opt { flag: "tp-mtp-depth", env: "GB10_TP_MTP_DEPTH", ty: Ty::Internal("--mtp-depth"), def: "unset", cat: Cat::Spec, scope: Scope::Spmd,
          help: "NVFP4 TP bench MTP depth (set by --mtp-depth)" },
    Opt { flag: "tp-oneshot", env: "GB10_TP_ONESHOT", ty: Ty::Flag, def: "off", cat: Cat::Tp, scope: Scope::Spmd,
          help: "TP=4 one-shot all-peers push" },
    Opt { flag: "tp-prefill-payload", env: "GB10_TP_PREFILL_PAYLOAD", ty: Ty::Int, def: "built-in", cat: Cat::Tp, scope: Scope::Spmd,
          help: "NVFP4 TP prefill all-reduce chunk cap (bytes)" },
    Opt { flag: "tp-prefill-xport", env: "GB10_TP_PREFILL_XPORT", ty: Ty::Choice(&["off", "0", "false", "single", "on", "1", "dual"]), def: "dual", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP prefill transport (off = serial pair, single = one rail, dual = both rails; dual is the default at every world, at --tp 4 the second rail is a full N-way link; single/off are loud perf opt-outs)" },
    Opt { flag: "tp-reduce-fuse", env: "GB10_TP_REDUCE_FUSE", ty: Ty::Bool, def: "auto (TpConfig)", cat: Cat::Tp, scope: Scope::Spmd,
          help: "NVFP4 TP fused reduce+residual+norm epilogue (on / off; unset = the shipped config)" },
    Opt { flag: "tp-route-fold", env: "GB10_TP_ROUTE_FOLD", ty: Ty::Bool, def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP route-ep fold into the router tail" },
    Opt { flag: "tp-shard-mixers", env: "GB10_TP_SHARD_MIXERS", ty: Ty::Internal("--tp (default) / --no-shard-mixers"), def: "on under TP", cat: Cat::Tp, scope: Scope::Spmd,
          help: "NVFP4 TP mixer sharding" },
    Opt { flag: "tp-shard-mtp", env: "GB10_TP_SHARD_MTP", ty: Ty::Bool, def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "NVFP4 TP MTP-block sharding" },
    Opt { flag: "tp-shared-repl", env: "GB10_TP_SHARED_REPL", ty: Ty::Flag, def: "off", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP replicated shared expert (diagnostic A/B)" },
    Opt { flag: "tp-spin-us", env: "GB10_TP_SPIN_US", ty: Ty::Int, def: "built-in", cat: Cat::Tp, scope: Scope::Spmd,
          help: "TP transport spin microseconds" },
    Opt { flag: "tp-state-tp", env: "GB10_TP_STATE_TP", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "TP GDN state probe" },
    Opt { flag: "tp-step-probe", env: "GB10_TP_STEP_PROBE", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "TP step probe" },
    Opt { flag: "tp-tail-drill", env: "GB10_TP_TAIL_DRILL", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "test drill: TP transport tail drill" },
    Opt { flag: "tp-trace", env: "GB10_TP_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "TP trace" },
    Opt { flag: "tp-vp-head", env: "GB10_TP_VP_HEAD", ty: Ty::Bool, def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP vocab-parallel lm_head for greedy rows" },
    Opt { flag: "tp-xport-blocks", env: "GB10_TP_XPORT_BLOCKS", ty: Ty::Int, def: "16", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP prefill transport blocks" },
    Opt { flag: "tp-xport-lookahead", env: "GB10_TP_XPORT_LOOKAHEAD", ty: Ty::Int, def: "4", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP prefill transport epochs in flight per rail" },
    Opt { flag: "trace-dequant", env: "GB10_TRACE_DEQUANT", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 dequant trace" },
    Opt { flag: "trace-prefill", env: "GB10_TRACE_PREFILL", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 prefill trace" },
    Opt { flag: "trace-wide", env: "GB10_TRACE_WIDE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 wide trace" },
    Opt { flag: "v2-det", env: "GB10_V2_DET", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 v2 determinism check" },
    Opt { flag: "verify-seq", env: "GB10_VERIFY_SEQ", ty: Ty::Flag, def: "off", cat: Cat::Dsv4, scope: Scope::Spmd,
          help: "DSV4 sequential verify" },
    Opt { flag: "w4a4-check", env: "GB10_W4A4_CHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "W4A4 check" },
    Opt { flag: "w4a4-lmhead-narrow", env: "GB10_W4A4_LMHEAD_NARROW", ty: Ty::Bool, def: "model config", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "W4A4 narrow lm_head (on / off; unset = the pack config)" },
    Opt { flag: "w4a4-n8", env: "GB10_W4A4_N8", ty: Ty::Bool, def: "on", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "W4A4 narrow 8-row MMA kernel (off = the wide 128-row kernel)" },
    Opt { flag: "w4a4-prefill", env: "GB10_W4A4_PREFILL", ty: Ty::Text, def: "unset", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "W4A4 prefill groups (expert,mlp,attn,gdn)" },
    Opt { flag: "w4a4-trace", env: "GB10_W4A4_TRACE", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "W4A4 trace" },
    Opt { flag: "w4a4-verify", env: "GB10_W4A4_VERIFY", ty: Ty::Text, def: "unset", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "W4A4 verify groups (attn,mlp,gdn)" },
    Opt { flag: "w4dense", env: "GB10_W4DENSE", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/DENSE package opt-in" },
    Opt { flag: "w4dense-fix", env: "GB10_W4DENSE_FIX", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/DENSE split-K fixup (tunable override)" },
    Opt { flag: "w4dense-g", env: "GB10_W4DENSE_G", ty: Ty::Text, def: "tuned", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/DENSE grid per shape" },
    Opt { flag: "w4dense-gsat", env: "GB10_W4DENSE_GSAT", ty: Ty::Int, def: "36", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/DENSE G-picker saturation (tunable override)" },
    Opt { flag: "w4dense-multi", env: "GB10_W4DENSE_MULTI", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/DENSE attention groups (tunable override)" },
    Opt { flag: "w4dense-nst", env: "GB10_W4DENSE_NST", ty: Ty::Choice(&["4", "6", "8"]), def: "6", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/DENSE ring depth (tunable override)" },
    Opt { flag: "w4dense-off", env: "GB10_W4DENSE_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/DENSE escape" },
    Opt { flag: "w4dense-silu", env: "GB10_W4DENSE_SILU", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/DENSE silu-down (tunable override)" },
    Opt { flag: "w4dense-suh", env: "GB10_W4DENSE_SUH", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/DENSE fused suh (tunable override)" },
    Opt { flag: "w4dense-xcheck", env: "GB10_W4DENSE_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "W4/DENSE eager cross-check" },
    Opt { flag: "w4hc-fuse", env: "GB10_W4HC_FUSE", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/HC regridded mixer (tunable override)" },
    Opt { flag: "w4hc-g", env: "GB10_W4HC_G", ty: Ty::Int, def: "96", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/HC grid target (tunable override)" },
    Opt { flag: "w4hc-inj", env: "GB10_W4HC_INJ", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/HC deferred inject + norm (tunable override)" },
    Opt { flag: "w4hc-la", env: "GB10_W4HC_LA", ty: Ty::Int, def: "0", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/HC phase-A L2 look-ahead 0..7 (tunable override)" },
    Opt { flag: "w4hc-m1", env: "GB10_W4HC_M1", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/HC at m = 1 (tunable override)" },
    Opt { flag: "w4hc-mix", env: "GB10_W4HC_MIX", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/HC mix fused behind the mixer (tunable override)" },
    Opt { flag: "w4hc-off", env: "GB10_W4HC_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/HC escape (tunable override)" },
    Opt { flag: "w4hc-pf", env: "GB10_W4HC_PF", ty: Ty::Choice(&["0", "1", "2"]), def: "1", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/HC phase-B L2 prefetch mode (tunable override)" },
    Opt { flag: "w4hc-xcheck", env: "GB10_W4HC_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "W4/HC eager cross-check" },
    Opt { flag: "w4moe", env: "GB10_W4MOE", ty: Ty::Flag, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/MOE package opt-in" },
    Opt { flag: "w4moe-g", env: "GB10_W4MOE_G", ty: Ty::Int, def: "0 (auto)", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/MOE persistent grid pin (tunable override)" },
    Opt { flag: "w4moe-minm", env: "GB10_W4MOE_MINM", ty: Ty::Int, def: "1", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/MOE min rows" },
    Opt { flag: "w4moe-nst", env: "GB10_W4MOE_NST", ty: Ty::Choice(&["4", "8"]), def: "0 (the plan rule)", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/MOE ring depth pin (tunable override)" },
    Opt { flag: "w4moe-off", env: "GB10_W4MOE_OFF", ty: Ty::Text, def: "unset", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/MOE escape (1|all|gu,dn,fold)" },
    Opt { flag: "w4moe-order", env: "GB10_W4MOE_ORDER", ty: Ty::Choice(&["il", "IL", "1", "0", "seq"]), def: "0 (seq)", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/MOE item order (il = interleaved; tunable override)" },
    Opt { flag: "w4moe-shovl", env: "GB10_W4MOE_SHOVL", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/MOE shared-expert overlap (tunable override)" },
    Opt { flag: "w4qsa", env: "GB10_W4QSA", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/QSA union gather opt-in" },
    Opt { flag: "w4qsa-off", env: "GB10_W4QSA_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/QSA escape" },
    Opt { flag: "w4qsa-xcheck", env: "GB10_W4QSA_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "W4/QSA eager cross-check" },
    Opt { flag: "w4s-off", env: "GB10_W4S_OFF", ty: Ty::Text, def: "unset", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "W4/SMALL escape (1|all|router,gdn,dattn,ple,draft)" },
    Opt { flag: "w4s-xcheck", env: "GB10_W4S_XCHECK", ty: Ty::Text, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "W4/SMALL eager cross-check (1|all|<parts>)" },
    Opt { flag: "wp01-off", env: "GB10_WP01_OFF", ty: Ty::Flag, def: "off", cat: Cat::Serve, scope: Scope::Spmd,
          help: "WP01 tokenizer cache escape" },
    Opt { flag: "wp01-xcheck", env: "GB10_WP01_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP01 tokenizer cache shadow check" },
    Opt { flag: "wp05-off", env: "GB10_WP05_OFF", ty: Ty::Text, def: "unset", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP05 escape (parts)" },
    Opt { flag: "wp05-xcheck", env: "GB10_WP05_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP05 eager cross-check" },
    Opt { flag: "wp09-argmax", env: "GB10_WP09_ARGMAX", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP09 one-launch argmax (tunable override)" },
    Opt { flag: "wp09-off", env: "GB10_WP09_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP09 umbrella escape (tunable override)" },
    Opt { flag: "wp09-ple", env: "GB10_WP09_PLE", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP09 k-major PLE (tunable override)" },
    Opt { flag: "wp09-xcheck", env: "GB10_WP09_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP09 eager cross-check" },
    Opt { flag: "wp10-gemv", env: "GB10_WP10_GEMV", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP10 GEMV lane remap (tunable override)" },
    Opt { flag: "wp10-off", env: "GB10_WP10_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP10 routing-fold escape (tunable override)" },
    Opt { flag: "wp10-xcheck", env: "GB10_WP10_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP10 eager cross-check" },
    Opt { flag: "wp11-cvt", env: "GB10_WP11_CVT", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP11 PRMT int8 convert (tunable override)" },
    Opt { flag: "wp11-off", env: "GB10_WP11_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP11 umbrella escape (tunable override)" },
    Opt { flag: "wp11-r1", env: "GB10_WP11_R1", ty: Ty::Choice(&["0", "1", "2"]), def: "1", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP11 R1 L2 prefetch mode (tunable override)" },
    Opt { flag: "wp11-r2", env: "GB10_WP11_R2", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP11 R2 regridded mix (tunable override)" },
    Opt { flag: "wp11-r3", env: "GB10_WP11_R3", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP11 R3 k-major q_up (tunable override)" },
    Opt { flag: "wp11-r4", env: "GB10_WP11_R4", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP11 R4 hn staging (tunable override)" },
    Opt { flag: "wp12-off", env: "GB10_WP12_OFF", ty: Ty::Text, def: "unset", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP12 escape (1|all|step,diet,conv,ab)" },
    Opt { flag: "wp12-xcheck", env: "GB10_WP12_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP12 eager cross-check" },
    Opt { flag: "wp16-off", env: "GB10_WP16_OFF", ty: Ty::Flag, def: "off", cat: Cat::Kv, scope: Scope::Spmd,
          help: "WP16 prefix-cache checkpoint escape" },
    Opt { flag: "wp16-probe-tail", env: "GB10_WP16_PROBE_TAIL", ty: Ty::Int, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP16 probe tail" },
    Opt { flag: "wp16-xcheck", env: "GB10_WP16_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP16 eager cross-check" },
    Opt { flag: "wp18-off", env: "GB10_WP18_OFF", ty: Ty::Flag, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP18 escape" },
    Opt { flag: "wp18-rows", env: "GB10_WP18_ROWS", ty: Ty::Int, def: "256", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP18 rows" },
    Opt { flag: "wp18-xcheck", env: "GB10_WP18_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP18 eager cross-check" },
    Opt { flag: "wp20-diet", env: "GB10_WP20_DIET", ty: Ty::Bool, def: "on", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP20 word diet (tunable override)" },
    Opt { flag: "wp20-epi", env: "GB10_WP20_EPI", ty: Ty::Text, def: "unset", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP20 epilogue rung (tunable override)" },
    Opt { flag: "wp20-off", env: "GB10_WP20_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP20 escape (tunable override)" },
    Opt { flag: "wp21-ks-off", env: "GB10_WP21_KS_OFF", ty: Ty::Text, def: "unset", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP21: listed ks keep the 3-launch tail" },
    Opt { flag: "wp21-off", env: "GB10_WP21_OFF", ty: Ty::Flag, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP21 escape" },
    Opt { flag: "wp21-xcheck", env: "GB10_WP21_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP21 eager cross-check" },
    Opt { flag: "wp22r1-off", env: "GB10_WP22R1_OFF", ty: Ty::Flag, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP22 R1 escape" },
    Opt { flag: "wp24-dump", env: "GB10_WP24_DUMP", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP24 sampler dump path" },
    Opt { flag: "wp24-xcheck", env: "GB10_WP24_XCHECK", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "WP24 sampler cross-check" },
    Opt { flag: "wp27-forks", env: "GB10_WP27_FORKS", ty: Ty::Text, def: "all", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP27 capture-DAG forks (all|none|<list>; tunable override)" },
    Opt { flag: "wp27-graphs", env: "GB10_WP27_GRAPHS", ty: Ty::Text, def: "all", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP27 graph classes (all|none|<list>; tunable override)" },
    Opt { flag: "wp27-off", env: "GB10_WP27_OFF", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP27 escape" },
    Opt { flag: "wp27-prio", env: "GB10_WP27_PRIO", ty: Ty::Bool, def: "off", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "WP27 node priorities (tunable override)" },
    Opt { flag: "xchain-ctx-dump", env: "GB10_XCHAIN_CTX_DUMP", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 cross-chain context dump path" },
    Opt { flag: "xchain-ctx-layers", env: "GB10_XCHAIN_CTX_LAYERS", ty: Ty::Text, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 cross-chain context layers" },
    Opt { flag: "xtp-floor-seeds", env: "GB10_XTP_FLOOR_SEEDS", ty: Ty::Int, def: "6", cat: Cat::Diag, scope: Scope::Spmd,
          help: "xtp floor probe seeds" },
    Opt { flag: "cpu-sample", env: "RUST_INFER_CPU_SAMPLE", ty: Ty::Flag, def: "off", cat: Cat::Serve, scope: Scope::Spmd,
          help: "sample on the CPU instead of the GPU" },
    Opt { flag: "dequant-at-load", env: "RUST_INFER_DEQUANT_AT_LOAD", ty: Ty::Flag, def: "off", cat: Cat::Load, scope: Scope::Spmd,
          help: "dequantize weights at load" },
    Opt { flag: "draft-vocab", env: "RUST_INFER_DRAFT_VOCAB", ty: Ty::Int, def: "full", cat: Cat::Spec, scope: Scope::Spmd,
          help: "FR-Spec draft vocabulary subset size (0 = full vocab)" },
    Opt { flag: "draft-vocab-file", env: "RUST_INFER_DRAFT_VOCAB_FILE", ty: Ty::Path, def: "unset", cat: Cat::Spec, scope: Scope::Spmd,
          help: "FR-Spec draft vocabulary row file" },
    Opt { flag: "dump-prompt", env: "RUST_INFER_DUMP_PROMPT", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Head,
          help: "server: dump rendered prompts" },
    Opt { flag: "dump-tokens", env: "RUST_INFER_DUMP_TOKENS", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Head,
          help: "server: dump tokens" },
    Opt { flag: "dump-tools", env: "RUST_INFER_DUMP_TOOLS", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Head,
          help: "server: dump tool parsing" },
    Opt { flag: "fake-quant", env: "RUST_INFER_FAKE_QUANT", ty: Ty::Text, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "fake-quant spec (layer:format,...)" },
    Opt { flag: "prefill-scalar", env: "RUST_INFER_PREFILL_SCALAR", ty: Ty::Flag, def: "off", cat: Cat::Nvfp4, scope: Scope::Spmd,
          help: "scalar prefill path" },
    Opt { flag: "zero-kv", env: "RUST_INFER_ZERO_KV", ty: Ty::Flag, def: "off", cat: Cat::Diag, scope: Scope::Spmd,
          help: "zero the KV cache at alloc" },
    Opt { flag: "pp-head-ip", env: "PP_HEAD_IP", ty: Ty::Text, def: "unset", cat: Cat::Tp, scope: Scope::Local,
          help: "PP prefill node: the head IP to dial" },
    Opt { flag: "dspark-synth-dir", env: "DSPARK_SYNTH_DIR", ty: Ty::Path, def: "built-in", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DSpark synthetic-table dir (offline tools)" },
    Opt { flag: "dflash2-synth-dir", env: "DFLASH2_SYNTH_DIR", ty: Ty::Path, def: "built-in", cat: Cat::Diag, scope: Scope::Spmd,
          help: "DFlash2 synthetic-table dir (offline tools)" },
    Opt { flag: "mtp-draft-log", env: "MTP_DRAFT_LOG", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 scheduler: per-step MTP draft log file" },
    Opt { flag: "mtp-curve-file", env: "MTP_CURVE_FILE", ty: Ty::Path, def: "unset", cat: Cat::Diag, scope: Scope::Spmd,
          help: "NVFP4 scheduler: MTP acceptance curve file" },
    Opt { flag: "tp-prefill-overlap", env: "", ty: Ty::Text, def: "dual:128 at TP=2", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP prefill all-reduce overlap: off|on|inline[:ROWS]|dual[:ROWS]|fold" },
    Opt { flag: "tp-vp-sampled", env: "", ty: Ty::Text, def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP=2/TP=4 vocab-parallel lm_head for sampled / penalized / ratio-rule rows (on|off; default on at world 2 and 4)" },
    Opt { flag: "tp-seq-parallel", env: "", ty: Ty::Text, def: "hc (on)", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP=2/TP=4 sequence-parallel prefill (on|hc|router|off); TP=4 = quarter rows (TP-4S)" },
    Opt { flag: "tp-lockstep-timeout-ms", env: "", ty: Ty::Int, def: "30000 at world > 2 (unused at world 2)", cat: Cat::Tp, scope: Scope::Head,
          help: "EXL3 TP world > 2: per-wait lockstep deadline in ms (peer alive but not progressing -> abort code 12); 0 = unbounded" },
    Opt { flag: "prefill-absorb-tail", env: "", ty: Ty::Flag, def: "on", cat: Cat::Kv, scope: Scope::Spmd,
          help: "EXL3 prefill (TP-4X1): fold a ragged (< recon-min rows) chunk into its neighbour when no checkpoint is lost beyond 16 rows (keeps the message-boundary tail checkpoint). ALWAYS on since v0.7.1 (owner 2026-10-02); the flag is accepted for older command lines and changes nothing" },
    Opt { flag: "tp-k2-prefetch", env: "", ty: Ty::Choice(&["on", "off"]), def: "on", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP=2/TP=4 decode (TP-4Z2): while a reduce's K2 waits for the peer, its idle threads pull the NEXT hc mixer's int8 weights into L2 (bitwise: a prefetch hint, no data path). on (default) | off" },
    Opt { flag: "tp-reduce", env: "", ty: Ty::Choice(&["auto", "rd", "single"]), def: "auto", cat: Cat::Tp, scope: Scope::Spmd,
          help: "EXL3 TP=4 decode/verify all-reduce (TP-4F2, default flipped by TP-4Z1): auto = single at world 4 (with the folded decode transport), rd elsewhere (default); rd = two recursive-doubling stages per reduce; single = ONE all-peers stage on a dedicated transport (bit-identical sum; third proxy thread on core 17, TCP base +40). `single` is refused at world != 4; prefill reduces are untouched" },
    Opt { flag: "tp-sync-only", env: "", ty: Ty::Flag, def: "off", cat: Cat::Tp, scope: Scope::Head,
          help: "B32: sync every node (blob cache), print the bytes each node needed and its cache footprint, then exit (head and nodes) — no model load. Rides TpConfig.sync_only" },
    Opt { flag: "qsa-key-rope", env: "", ty: Ty::Choice(&["half", "full"]), def: "full", cat: Cat::Exl3, scope: Scope::Spmd,
          help: "EXL3 QSA indexer (past 2051 visible tokens): full = rope the pooled block keys over all rotary dims (the reference; NVFP4 engine's table; default, owner 2026-10-02); half = the old table that left dims rdim/2..rdim at zero (pre-v0.7.1 bytes, for A/B only). Output-changing past the dense window" },
    Opt { flag: "host", env: "", ty: Ty::Text, def: "0.0.0.0", cat: Cat::Serve, scope: Scope::Head,
          help: "HTTP API bind address: an IPv4/IPv6 address or a host name (e.g. 127.0.0.1 = this machine only). 0.0.0.0 (default) = every interface" },
    Opt { flag: "image-max-edge", env: "", ty: Ty::Int, def: "1024", cat: Cat::Serve, scope: Scope::Head,
          help: "vision (D-VIS-RESIZE, owner 2026-09-30): every input image is resized so its LONGER side is at most N px, aspect ratio kept, before the model's own 32-px grid snap; never a size 400. 0 = no cap (the preprocessor's 16.7 MP limit still applies)" },
];

/// Environment variables that were read once and are gone (merged into an existing flag, or dead):
/// the startup guard names the replacement.
pub const REMOVED: &[(&str, &str)] = &[
    ("DSV4_BISECT_LEN", "--bisect-len <N>"),
    ("DSV4_MAX_SEQ_LEN", "--max-seq-len <N>"),
    ("DSV4_PREFILL_TRACE", "--prefill-trace"),
    ("GB10_DF2_STEP_DUMP", "--df2-step-dump <DIR>"),
    ("GB10_NODE_CHILD", "nothing (the node supervisor passes --once to its session child)"),
    ("GB10_WP27_TEST_LIST", "nothing (a unit-test-only knob, removed)"),
    ("RUST_INFER_GPU_SAMPLE", "nothing (GPU sampling is the default; --cpu-sample is the escape)"),
    ("RUST_INFER_MTP", "--mtp on|off"),
    ("RUST_INFER_MTP_STOCHASTIC", "--mtp on|off"),
    ("GB10_DFLASH_DIR", "--draft-dir <DIR> (the deprecated --dflash-dir spelling for the v1 source)"),
];
